/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\assets\ibda_platform_v1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ibda_platform_v1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cube006.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/ibda_platform_v1.glb')
